In [2]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

import joblib

In [4]:
df = pd.read_csv("../dataset/UNSW_NB15_training-set.csv")

df.head()

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

In [5]:
df = df.drop(columns=["id"])

df.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,0.000011,udp,-,INT,2,0,496,0,90909.0902,254,...,1,2,0,0,0,1,2,0,Normal,0
1,0.000008,udp,-,INT,2,0,1762,0,125000.0003,254,...,1,2,0,0,0,1,2,0,Normal,0
2,0.000005,udp,-,INT,2,0,1068,0,200000.0051,254,...,1,3,0,0,0,1,3,0,Normal,0
3,0.000006,udp,-,INT,2,0,900,0,166666.6608,254,...,1,3,0,0,0,2,3,0,Normal,0
4,0.000010,udp,-,INT,2,0,2126,0,100000.0025,254,...,1,3,0,0,0,2,3,0,Normal,0

In [6]:
df.isnull().sum()

dur                  0
proto                0
service              0
state                0
spkts                0
dpkts                0
sbytes               0
dbytes               0
rate                 0
sttl                 0
dttl                 0
sload                0
dload                0
sloss                0
dloss                0
sinpkt               0
dinpkt               0
sjit                 0
djit                 0
swin                 0
stcpb                0
dtcpb                0
dwin                 0
tcprtt               0
synack               0
ackdat               0
smean                0
dmean                0
trans_depth          0
response_body_len    0
ct_srv_src           0
ct_state_ttl         0
ct_dst_ltm           0
ct_src_dport_ltm     0
ct_dst_sport_ltm     0
ct_dst_src_ltm       0
is_ftp_login         0
ct_ftp_cmd           0
ct_flw_http_mthd     0
ct_src_ltm           0
ct_srv_dst           0
is_sm_ips_ports      0
attack_cat           0
label                0
dtype: int64

In [7]:
df = df.drop_duplicates()

df.shape

(55945, 44)

In [9]:
X = df.drop("label", axis=1)

y = df["label"]

In [10]:
X.head()

,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,sttl,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat
0,0.000011,udp,-,INT,2,0,496,0,90909.0902,254,...,1,1,2,0,0,0,1,2,0,Normal
1,0.000008,udp,-,INT,2,0,1762,0,125000.0003,254,...,1,1,2,0,0,0,1,2,0,Normal
2,0.000005,udp,-,INT,2,0,1068,0,200000.0051,254,...,1,1,3,0,0,0,1,3,0,Normal
3,0.000006,udp,-,INT,2,0,900,0,166666.6608,254,...,2,1,3,0,0,0,2,3,0,Normal
4,0.000010,udp,-,INT,2,0,2126,0,100000.0025,254,...,2,1,3,0,0,0,2,3,0,Normal

In [11]:
y.value_counts()

label
0    34206
1    21739
Name: count, dtype: int64

In [15]:
# Convert text columns to numbers using One-Hot Encoding
X = pd.get_dummies(X, columns=['proto', 'service', 'state'], drop_first=True)

# Check the result
print("New shape:", X.shape)
print("Columns are now all numeric:")
print(X.head())

New shape: (55945, 188)
Columns are now all numeric:
        dur  spkts  dpkts  sbytes  dbytes         rate  sttl  dttl  \
0  0.000011      2      0     496       0   90909.0902   254     0
1  0.000008      2      0    1762       0  125000.0003   254     0
2  0.000005      2      0    1068       0  200000.0051   254     0
3  0.000006      2      0     900       0  166666.6608   254     0
4  0.000010      2      0    2126       0  100000.0025   254     0

         sload  dload  ...  service_9  service_10  service_11  service_12  \
0  180363632.0    0.0  ...      False       False       False       False
1  881000000.0    0.0  ...      False       False       False       False
2  854400000.0    0.0  ...      False       False       False       False
3  600000000.0    0.0  ...      False       False       False       False
4  850400000.0    0.0  ...      False       False       False       False

   state_1  state_2  state_3  state_4  state_5  state_6
0    False    False    False     True    False    False
1    False    False    False     True    False    False
2    False    False    False     True    False    False
3    False    False    False     True    False    False
4    False    False    False     True    False    False

[5 rows x 188 columns]

In [16]:
from sklearn.preprocessing import StandardScaler
import joblib

# Initialize scaler
scaler = StandardScaler()

# Fit and transform the data
X_scaled = scaler.fit_transform(X)

# Save the scaler for later use in your app
joblib.dump(scaler, "../models/scaler.pkl")

print("✓ Scaling complete!")
print("✓ Scaler saved to ../models/scaler.pkl")
print("Scaled data shape:", X_scaled.shape)

ValueError: could not convert string to float: 'Normal'

In [1]:
print("python working")

python working